### ISSUE TITLE
Greedy org-protocol handler.  Killing client.

### ISSUE THREAD

**Issue by brunoqc** [sprig/org-capture-extension#1]
I get this in emacs when I click the button :

```
Greedy org-protocol handler.  Killing client.
No server buffers remain to edit
```

GNU Emacs 24.4.1 (x86_64-w64-mingw32) of 2014-10-20 on KAEL

**Comment by sprig** [comment]
Hi!

This looks as though you have an error in your handler (i.e. capture template). Could you post your capture templates please?

**Comment by brunoqc** [comment]
Sorry for the very late reply.

I just tried the capture template from http://orgmode.org/worg/org-contrib/org-protocol.html#sec-6-1 . I also tried with org-capture-templates as nil.
```lisp
(setq org-capture-templates
      (quote
       (("w"
         "Default template"
         entry
         (file+headline "~/org/capture.org" "Notes")
         "* %^{Title}\n\n  Source: %u, %c\n\n  %i"
         :empty-lines 1)
        ;; ... more templates here ...
        )))
```

GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-05-16 on KAEL

**Comment by sprig** [comment]
You need to have the handler handle "L" (for links) or "p" (for selected text respectively. Thanks means that on the third line of your quote you would put "p".

Please refer to https://github.com/sprig/org-capture-extension#set-up-handlers-in-emacs

**Comment by brunoqc** [comment]
It works, thanks!

**Comment by lkmokadam** [comment]
I was having the same issue. But this doesn't work for me. 
Solved it using this link https://lists.gnu.org/archive/html/emacs-orgmode/2010-08/msg01282.html

**Comment by vzaliva** [comment]
> I was having the same issue. But this doesn't work for me.
> Solved it using this link https://lists.gnu.org/archive/html/emacs-orgmode/2010-08/msg01282.html

If there is a way to achieve this externally (in .emacs) without changing org-protocol.el files? they will be overwritten on updates by package manger...

**Comment by vzaliva** [comment]
never mind, it is `nil` in the most recent org-mode.

**Comment by vanangamudi** [comment]
Leaving this note here in case someone else face this issue. It can also happen if the file does not contain the respective heading in the org file.

The heading must be present in the file as configured in the capture templates. The entry that is declared in the capture templates must exist in the file. 

i.e =Collection=, must exist in the =collection.org= file.

```

   ("c" "Collection" plain 
           (file+olp "~/org/collection.org" "Collection")
           "** %a\n %?\n %i")

```
