### ISSUE TITLE
Would like to close emacs window automatically

### ISSUE THREAD

**Issue by monokinetic** [sprig/org-capture-extension#11]
Hi,
you mention in the docs that you can use %() blocks with L to automatically close the opened capture window. I'm not sure if this is what I want, but basically I want to add my L template to my links.org file automatically. So I use :immediate-finish in the capture template and that works well. But I've not found a way to kill the opened extra emacs window that opened.

Any suggestions how to do that please?

**Comment by sprig** [comment]
I do it in a somewhat convoluted way, but it works. 

As I recall, I set a capture completion or a file save hook that checks a variable and depending on the value of the variable kills the current frame after resetting its value. In the capture template I run a piece of code that sets the variable.

I will fish this piece later and post it, if you wish.

**Comment by monokinetic** [comment]
Aha OK, that's not a tactic I have tried. If you have time to post an example that would be great!

**Comment by sprig** [comment]
The capture template is 
```
                                ("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
                                 "* %? [[%:link][%:description]] %(progn (setq kk/delete-frame-after-capture 2) \"\")\nCaptured On: %U"
                                 :empty-lines 1)
```

In the initialization of org-mode I have the following:

```
  ;; Kill the frame if one was created for the capture
  (defvar kk/delete-frame-after-capture 0 "Whether to delete the last frame after the current capture")

  (defun kk/delete-frame-if-neccessary (&rest r)
    (cond
     ((= kk/delete-frame-after-capture 0) nil)
     ((> kk/delete-frame-after-capture 1)
      (setq kk/delete-frame-after-capture (- kk/delete-frame-after-capture 1)))
     (t
      (setq kk/delete-frame-after-capture 0)
      (delete-frame))))

  (advice-add 'org-capture-finalize :after 'kk/delete-frame-if-neccessary)
  (advice-add 'org-capture-kill :after 'kk/delete-frame-if-neccessary)
  (advice-add 'org-capture-refile :after 'kk/delete-frame-if-neccessary)
```

Don't ask me right now why I did it in a two stage fashion - I didn't document it unfortunately, but it works. Good luck!

**Comment by sprig** [comment]
Reopening in order to add this to the readme.

**Comment by wigust** [comment]
Why just not use `:immediate-finish t`?
```
("p" "Protocol" entry (file+headline (concat org-directory "/links.org") "Links")
"* %U %c\n#+BEGIN_QUOTE\n%i\n#+END_QUOTE"
:immediate-finish t)
```

**Comment by sprig** [comment]
@wigust read the OP

**Comment by bleggett** [comment]
Would like to point out that you can avoid the creation of new frames in the first place by removing the `-c` argument from the `emacsclient` invocation.

Then no transient windows are created, capture works using the existing emacs window, and you don't need the above workaround.

**Comment by sprig** [comment]
It’s a good point, but then you encounter a different problem; Emacs stays in the background during capture...

**Comment by bleggett** [comment]
Yes, it only makes sense if you always keep an Emacs window open anyway (which I do)

**Comment by sprig** [comment]
I do as well, but you still need to switch to it. This can be more of a problem if you keep more than one window open.

**Comment by Sabicool** [comment]
> The capture template is
> 
> ```
>                                 ("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
>                                  "* %? [[%:link][%:description]] %(progn (setq kk/delete-frame-after-capture 2) \"\")\nCaptured On: %U"
>                                  :empty-lines 1)
> ```
> 
> In the initialization of org-mode I have the following:
> 
> ```
>   ;; Kill the frame if one was created for the capture
>   (defvar kk/delete-frame-after-capture 0 "Whether to delete the last frame after the current capture")
> 
>   (defun kk/delete-frame-if-neccessary (&rest r)
>     (cond
>      ((= kk/delete-frame-after-capture 0) nil)
>      ((> kk/delete-frame-after-capture 1)
>       (setq kk/delete-frame-after-capture (- kk/delete-frame-after-capture 1)))
>      (t
>       (setq kk/delete-frame-after-capture 0)
>       (delete-frame))))
> 
>   (advice-add 'org-capture-finalize :after 'kk/delete-frame-if-neccessary)
>   (advice-add 'org-capture-kill :after 'kk/delete-frame-if-neccessary)
>   (advice-add 'org-capture-refile :after 'kk/delete-frame-if-neccessary)
> ```
> 
> Don't ask me right now why I did it in a two stage fashion - I didn't document it unfortunately, but it works. Good luck!

Very late to the party but I don't see why you can just use the `:after-finalize` option in the capture template. For example like this:

```
("l" "Protocol Link" plain (file ,(concat org-gtd-directory "inbox.org"))
   "* %? :Web_Link:\nCaptured on: %U, from %:link\n"
   :after-finalize (lambda () (delete-frame)))
```

**Comment by AdelleBernal** [comment]
I still have to delete the frame manually because when the `emacsclient` frame is closed, the focus shifts away from the other Emacs frame where I am saving. I'm not sure how to address this issue so that I don’t have to switch to Emacs while browsing and capturing text and links. Do you have any solutions?
