### ISSUE TITLE
Percent/Url encoding

### ISSUE THREAD

**Issue by fjp** [sprig/org-capture-extension#13]
Hi,

I've setup your nice chrome capture extension on mac osx using EmacsClient.app and spacemacs.
Everything seemed to work except for URLs that include % signs to escape special characters. 
(e.g. https://en.wikipedia.org/wiki/Pontryagin%27s_maximum_principle)

When pressing the button of the org-capture-extension in chrome, EmacsClient shortly "starts"/flashes up but there is No reaction in spacemacs (with and without text selected).

This is the output of the chrome developer console:
`Capturing the following URI with org-protocol: org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagi…gin's%20maximum%20principle%20-%20Wikipedia%2C%20the%20free%20encyclopedia`

I guess the apostrophe in "Pontryagin**'**s" is a problem.

I tried also directly with emacsclient on the terminal but I couldn't figure out the correct command:
`emacsclient "'org-protocol:/capture:/L/https://en.wikipedia.org/wiki/Pontryagin%27s_maximum_principle/Pontryagin's maximum principle "'"`
Although this fires up spacemacs...

Can you tell me if this is an issue with the org-capture-extension code or should I escape the %-sign using my capture templates?

**Comment by sprig** [comment]
Hi,

You are not supposed to do additional escaping, unless there is a bug of course. As far as I remember, when the window flashes and closes, it means a problem with the capture template - but don't take my word for it.

I tried capturing this page on windows, and it worked. However, I do notice that there is an unescaped quote in the text and I suspect it might be the source of the problem. Please try the following commands in a terminal, and let me know what happens in each case:

```
emacsclient org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagin

open org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagin

open org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagins%20maximum%20principle%20-%20Wikipedia%2C%20the%20free%20encyclopedia

open org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagin's%20maximum%20principle%20-%20Wikipedia%2C%20the%20free%20encyclopedia
```

I will also investigate why the quote does not get escaped. Right now it looks to me like a bug.

**Comment by sprig** [comment]
Please download the branch [13-encode-title](https://github.com/sprig/org-capture-extension/tree/13-encode-title) and try that version.

You install an unpacked extension by dragging the folder onto the extensions page in chrome. Please disable temporarily the standard extension so that you don't get confused as to which icon is which.

**Comment by fjp** [comment]
Thanks for your help,

using the changes from the [13-encode-title](https://github.com/sprig/org-capture-extension/tree/13-encode-title) branch it is working!



Executing the first three commands

```
emacsclient org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagin

open org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagin

open org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagins%20maximum%20principle%20-%20Wikipedia%2C%20the%20free%20encyclopedia
```
works perfect: The capture buffer is opened and Title and Link are set accordingly.


When pressing enter for the last command:
```
open org-protocol://capture:/L/https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPontryagin%2527s_maximum_principle/Pontryagin's%20maximum%20principle%20-%20Wikipedia%2C%20the%20free%20encyclopedia
```
the terminal promt changes to `quote>`

**Comment by sprig** [comment]
Great. It looks like it works on OSX here as well. I'll merge this and push the update to the chrome store.
