### ISSUE TITLE
Operation not supported chromium-56.0.2924.87 Fedora 25

### ISSUE THREAD

**Issue by wigust** [sprig/org-capture-extension#21]
I'm trying to solve `Operation not supported` issue on chromium. If somebody have any thoughts please let me know

`Fedora 25 (Workstation Edition)
chromium-56.0.2924.87-3.fc25.x86_64`

journalctl output:
`Mar 28 00:11:25 magnolia.local chromium-browser.desktop[10055]: gio: org-protocol://capture:/p/https%3A%2F%2Fstackoverflow.com%2Fquestions%2F11494232%2Fwhy-is-chrome-browseraction-onclicked-undefined/javascript%20-%20Why%20is%20chrome.browserAction.onClicked%20undefined%3F%20-%20Stack%20Overflow/-%20Use%20variables%20or%20functions%20defined%20by%20their%20extension%27s%20pages%0A: Operation not supported`

**Comment by wigust** [comment]
Stupid me. I forgot about: `update-desktop-database ~/.local/share/applications/`. Now it works.

**Comment by sprig** [comment]
Glad it worked out :-)
