### ISSUE TITLE
No proper text escaping

### ISSUE THREAD

**Issue by SzymonPajzert** [sprig/org-capture-extension#22]
Selecting text:

The gist of it is to make your system recognize emacsclient as the handler of org-protocol:// links. In addition, one needs to set up emacs to load org-protocol and to set up capture templates.

Blows my capture up

**Comment by sprig** [comment]
Maybe write in a couple of words what made you change you mind, for the sake of others?

**Comment by SzymonPajzert** [comment]
Bad configuration of org-protocol was the reason of the error, no problem in escaping the strings.
