### ISSUE TITLE
Needs a keybinding

### ISSUE THREAD

**Issue by mdorman** [sprig/org-capture-extension#24]
This has worked great for me so far; thanks for making it available.

The one thing I miss versus the old extension is a keybinding---being an aged Emacser, my relationship with the mouse is spotty at best.

**Comment by sprig** [comment]
Thanks @mdorman!

See PR #19 regarding keybindings. There is currently no special UI to change it - you can change it from the extensions page (a PR for an options page where you can change the binding would be more than welcome ;-)

**Comment by adamist521** [comment]
Thanks for nice extension!

Somehow shortcut is not working...
Able to set shortcut on chrome but wouldn't fire capture.
Works perfect by clicking extension button!

Env is follows.
```Chrome 62.0.3202.62 (Official Build) (64 bit), macOS 10.12.4```
