### ISSUE TITLE
Greedy handler issue when no problem with org-capture template -- on Firefox Quantum and Chrome

### ISSUE THREAD

**Issue by 00krishna** [sprig/org-capture-extension#39]
Hello @sprig, how are you doing? 

This issue is actually closed now, but I wanted to make sure I communicated an issue that affects the extension. Looks like there were some recent changes to the Emacs `use-package` package, which was interfering with the org-capture templates. Here is the link to the issue 

https://github.com/jwiegley/use-package/issues/557

Let me tell you how I found the issue in case you get other people registering similar issues. 

I set up the org-capture-extension as you recommended in the README, however I keep getting the following error (posted below) in emacs *Messages* buffer. I am using Emacs 25.3 on Ubuntu 16.04x64 with the new Firefox Quantum browser as well as Chrome. 

```
Greedy org-protocol handler.  Killing client. 
No server buffers remain to edit.
```
So I tried to manually pass a link through the `emacsclient` with the following command

```
emacsclient -n "org-protocol:///capture?url=http%3a%2f%2fduckduckgo%2ecom&title=DuckDuckGo"
```
But I kept getting this strange response in the *Messages* buffer where there was a cycling behavior between warning349 and warning 931.

```
condition-case: Symbol’s value as variable is void: use-package--warning349
condition-case: Symbol’s value as variable is void: use-package--warning931
condition-case: Symbol’s value as variable is void: use-package--warning349
condition-case: Symbol’s value as variable is void: use-package--warning931
condition-case: Symbol’s value as variable is void: use-package--warning349
```

Let me know if you have any questions.

**Comment by 00krishna** [comment]
You can mark this closed. I just wanted to let you change the status after you saw it.

**Comment by sprig** [comment]
Thanks for the heads up!
