### ISSUE TITLE
Org captue results in Emacs opening ~/org-capture/... file instead of triggering org-capture

### ISSUE THREAD

**Issue by vmalloc** [sprig/org-capture-extension#40]
I'm using the default configuration on the emacs side (`(require org-protocol)`).

I got the bookmarklet working correctly from chrome:
```
javascript:(function () {   window.location.href='org-protocol://capture://l/'     +encodeURIComponent(window.location.href)+'/'     +encodeURIComponent(document.title)+'/'     +encodeURIComponent(window.getSelection()); })();
```

However the extension doesn't work on both FF and Chrome - it sends me to an empty buffer that is being opened as ~/org-protocol:/capture/?template=l&url=XXX

I think the URL formatted by the bookmarklet is the more "correct" one as it works correctly both through xdg-open and through the bookmarklet in Chrome...

**Comment by sprig** [comment]
This extension by default uses different handlers than the default setup (specifically, for `p` as in paragraph when you have made a selection, and `L` for link when you haven't).

See https://github.com/sprig/org-capture-extension#set-up-handlers-in-emacs for more details.

**Comment by sprig** [comment]
If you have further problems with this issue feel free to reopen the ticket, but please follow the instructions outlined here;

https://github.com/sprig/org-capture-extension#troubleshooting
