### ISSUE TITLE
Frame visibility on top

### ISSUE THREAD

**Issue by fleimgruber** [sprig/org-capture-extension#46]
The Emacs capture frame opens but is hidden by the browser (Firefox) window.  I am using macOS so went with the Applescript handler.  Is there a way to display the capture frame on top of the other windows?  Or switch to the frame directly?

**Comment by dangom** [comment]
I couldn't work around the issue so I just hacked away with [Hammerspoon.](https://github.com/Hammerspoon/hammerspoon)

Add the following to your `init.lua`:

```lua
function emacsclientWatcher(appName, eventType, appObject)
  if (eventType == hs.application.watcher.activated) then
    if (appName == "Emacsclient") then
      -- Bring Emacs to Front
      hs.osascript.applescript('tell application "Emacs" to activate')
    end
  end
end
appWatcher = hs.application.watcher.new(emacsclientWatcher)
appWatcher:start()
```

**Comment by sprig** [comment]
Nice workaround @dangom, thanks!
@fleimgruber Did that work for you? If not, could you be more specific regarding which `Applescript handler` you are referring to?

**Comment by fleimgruber** [comment]
I ended up doing the capture in Org mode directly, so did not try this again. Feel free to close if the workaround is good enough for you

**Comment by sprig** [comment]
Just curious, what do you mean by "directly"?
-- 
-- 
Konstantin Kliakhandler
    http://slumpy.org
          )°) )°( (°(

**Comment by fleimgruber** [comment]
Sure, I use a variant of https://www.reddit.com/r/emacs/comments/83frxm/reading_managing_annotating_and_highlighting/dvhi9ba/

**Comment by sprig** [comment]
So basically copy-paste?
-- 
-- 
Konstantin Kliakhandler
    http://slumpy.org
          )°) )°( (°(

**Comment by fleimgruber** [comment]
Yes, it was the lowest common denominator across reading feeds, emails and browser.

**Comment by cartoonist** [comment]
Just for the record regarding the Hammerspoon workaround, the `appName` comparison is case-sensitive. I had to rename "Emacsclient" to "EmacsClient" for the script to work.
