### ISSUE TITLE
capture info shows up in buffer name

### ISSUE THREAD

**Issue by zouhx11** [sprig/org-capture-extension#48]
<img width="762" alt="2018-06-13 1 59 30" src="https://user-images.githubusercontent.com/12454682/41308957-e0d5673e-6eaf-11e8-8920-599d8aef9cb7.png">
as shown in figure, I can't figure out why it fails to capture.

**Comment by sprig** [comment]
It looks like you did not set up the emacs portion. Did you follow https://github.com/sprig/org-capture-extension#set-up-handlers-in-emacs ?

**Comment by 1994668171** [comment]
@zouhx11 Did you fix it?

**Comment by MuriloHMoreira** [comment]
I am having the same issue, it was working last time I tried it (maybe some months ago).

**Comment by Moanrisy** [comment]
I am having this issue too

**Comment by Moanrisy** [comment]
> It looks like you did not set up the emacs portion. Did you follow https://github.com/sprig/org-capture-extension#set-up-handlers-in-emacs ?

@sprig I do already setup it, already change the org url too

**Comment by jf-parent** [comment]
I had the same issue and adding `(require 'org-protocol)` in my emacs config solved the problem (ref: https://blog.aaronbieber.com/2016/11/24/org-capture-from-anywhere-on-your-mac.html).
