### ISSUE TITLE
Is the README outdated?

### ISSUE THREAD

**Issue by memeplex** [sprig/org-capture-extension#51]
No matter whether there is a selection or not I get a `p` capture template and the format is not the same as documented:

```
org-protocol://capture?template=p&url=https%3A%2F%2Fgithub.com%2Fsprig%2Forg-capture-extension&title=sprig%2Forg-capture-extension%3A%20A%20Chrome%20and%20firefox%20extension%20facilitating%20org-capture%20in%20emacs&body=If%20some%20text%20is%20selected%20before%20the%20button%20is%20clicked%2C%20then%20the%20following%20is%20sent%20to%20emacs%3A%0A%0A

org-protocol://capture?template=p&url=https%3A%2F%2Fdeveloper.gnome.org%2Fdesktop-entry-spec%2F&title=Desktop%20Entry%20Specification&body=%25u
```

**Comment by sprig** [comment]
Sorry for the long delay in responding.

The Readme should be updated. I am unable to reproduce your purported misbehavior;

Specifically, after enabling debug output, I see the following when goint to developer.gnome.org/desktop-entry-spec/ and clicking the extension button:

```Capturing the following URI with new org-protocol:  org-protocol://capture?template=L&url=https%3A%2F%2Fdeveloper.gnome.org%2Fdesktop-entry-spec%2F&title=Desktop%20Entry%20Specification&body=```

It appears as though your version as an additional `%25u` that got into the the selection somehow, which is the cause of the error.

You are welcome to create a new ticket with appropriate level of details if you are still experiencing the problem. The readme states the required info.

Good luck!
