### ISSUE TITLE
getting the extension to talk to emacs

### ISSUE THREAD

**Issue by mhlr** [sprig/org-capture-extension#6]
I am running chrome-8.0 and emacs25 on Linux Mint.

I have installed the extension from the chrome store,
I have an emacs server running that emacsclient can connect to
and  I executed:

    gconftool-2 -s /desktop/gnome/url-handlers/org-protocol/command '/usr/local/bin/emacsclient %s' --type String
    gconftool-2 -s /desktop/gnome/url-handlers/org-protocol/enabled --type Boolean true

on my machine as stated in the org-protocol docs.

When I click the extesion's button I get a pop-up saying it wants to open the link with xdg-open.
What do I need to do to get it to talk to the emacs server instead?

**Comment by sprig** [comment]
Hello Daniel,

This is the way it is supposed work. You should agree to open with
xdg-open, which is what dispatches to the other programs, according to
configuration, in linux. If I remember correctly, you should only see this
once.

**Comment by sprig** [comment]
If you need additional help, please reopen or create an additional issue.

**Comment by mfiano** [comment]
I get the same thing, asking to open with xdg-open, and then it just opens up a new chrome window with an empty tab...never issuing a call emacsclient.

**Comment by sprig** [comment]
It sounds as though emacsclient isn't registered as the handler for org-protocol. Did you follow the instructions on the org-mode site for registering it?

What happens if you try to copy the link address, and `xdg-open the-link-address` in a terminal?

**Comment by mfiano** [comment]
I followed the directions exactly, and using xdg-open from the terminal results in the same thing - a new chromium window opening with a blank tab

**Comment by sprig** [comment]
Ok, so if it already doesn't work in the terminal, it is out of my scope...

However, did you try a logout/login back after following the instructions? What distro + desktop environment + window manager are you using? Maybe I will have an idea by chance...

**Comment by mfiano** [comment]
I did try that. I am using Arch Linux, no DE, just i3wm.

**Comment by sprig** [comment]
If this is Arch+no DE, quite possibly you need to install some package that parses .desktop files and registers them.

Did you try the instructions from [https://github.com/sprig/org-capture-extension#register-emacsclient-as-the-org-protocol-handler](here), which I believe are not exactly the same as those on the org-mode site?

If so, I suggest you prowl arch wiki and their IRC channel regarding the necessary packages to register a handler for xdg-open. If you send the instructions later, I will add them for the benefit of others.
