### ISSUE TITLE
Can't open the emacs client

### ISSUE THREAD

**Issue by jinboowu** [sprig/org-capture-extension#79]
windows 10 OS with spacemacs 
As I select the content and click the extension button, the firefox browser showed "captured"

but he emacs client doesn't have any response, and no content was added to the target file.  

my configuration:

(server-start)
(require 'org-protocol)

  (add-to-list 'org-modules 'org-protocol)

  (setq org-capture-templates `(
	("p" "Protocol" entry (file+headline ,(concat org-directory "note.org") "web")
        "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
	("L" "Protocol Link" entry (file+headline ,(concat org-directory "note.org") "web")
        "* %? [[%:link][%:description]] \nCaptured On: %U")
))

**Comment by articuluxe** [comment]
Can you open emacsclient and connect to a running server instance from a shell, or outside of the browser?

**Comment by sprig** [comment]
Since there has been no reply from OP in a long time I will close. Feel free to reopen.
