### ISSUE TITLE
Capture broken with Chrome 120? Chrome extension changes?

### ISSUE THREAD

**Issue by hrehfeld** [sprig/org-capture-extension#85]
chrome version: Version 120.0.6099.224 (Official Build) (64-bit)

org-capture just started:
a) not to ask if opening `xdg-open` is ok (not sure what the exact message was)
b) not calling `xdg-open`

### example console output:
```
Capturing the following URI with new org-protocol:  org-protocol://capture?template=L&url=https%3A%2F%2Fgithub.com%2F&title=GitHub%3A%20Let%E2%80%99s%20build%20from%20here%20%C2%B7%20GitHub&body=
```

This same line prepended with xdg-open just works on the shell and starts a capture process.

No further console messages. Not sure how to proceed collecting further info.

(This is a relatively urgent request as my daily workflow depends on this extension)

**Comment by sprig** [comment]
Sorry, I've been somewhat away for a while. Nice to hear that you find/found the extension useful!

I'm using Chrome 124.0.6367.63 (Official Build) (64-bit). And for me the extension continues working. I do get asked by chrome whethere I want to allow the extension to open emacs, but if I confirm, then emacs opens as usual. As far as I understand this relates to new security measures by chrome. 
![Screenshot 2024-05-01 111004](https://github.com/sprig/org-capture-extension/assets/2652983/4bbde4d7-4ad2-4abe-9268-9db85ed319d5)

Did you get it to work?

**Comment by sprig** [comment]
Closing as no response. If you need more help, let me know.
